//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorHoteleiro.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.HOSPEDAGEM = new HashSet<HOSPEDAGEM>();
        }
    
        public int NNUMECLIENTE { get; set; }
        public string CNOME { get; set; }
        public string CCPF { get; set; }
        public string CRG { get; set; }
        public Nullable<System.DateTime> DDATANASC { get; set; }
        public Nullable<System.DateTime> DDATACADASTRO { get; set; }
        public string COBSERVACAO { get; set; }
        public string CCEP { get; set; }
        public string CCIDADE { get; set; }
        public string CUF { get; set; }
        public string CRUA { get; set; }
        public string CBAIRRO { get; set; }
        public string CFONE { get; set; }
        public string CFONE2 { get; set; }
        public string CEMAIL { get; set; }
    
        public virtual ICollection<HOSPEDAGEM> HOSPEDAGEM { get; set; }
    }
}
