//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorHoteleiro.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSUMO
    {
        public int NIDCONSUMO { get; set; }
        public int NIDHOSPEDAGEM { get; set; }
        public int NIDITEMCONSUMO { get; set; }
        public Nullable<int> NQUANTIDADE { get; set; }
        public Nullable<decimal> NVALORBRUTO { get; set; }
        public Nullable<System.DateTime> DDATAHORA { get; set; }
    }
}
