//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorHoteleiro.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSPEDAGEM
    {
        public int NIDHOSPEDAGEM { get; set; }
        public int NIDCLIENTE { get; set; }
        public int NIDQUARTO { get; set; }
        public Nullable<System.DateTime> DDATAIN { get; set; }
        public Nullable<System.DateTime> DDATAOUT { get; set; }
        public string CESTATUS { get; set; }
        public string COBSERVACAO { get; set; }
        public string FFORMAPAGAMENTO { get; set; }
        public Nullable<decimal> VVALORTOTAL { get; set; }
        public Nullable<decimal> VVALORDESCONTO { get; set; }
        public Nullable<System.DateTime> DDATAFECHAMENTO { get; set; }
        public Nullable<int> NDIARIAS { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual QUARTO QUARTO { get; set; }
    }
}
