//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorHoteleiro.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTEL
    {
        public int NIDHOTEL { get; set; }
        public string CNOME { get; set; }
        public string CCNPJ { get; set; }
        public string CINSC { get; set; }
        public string CFONE { get; set; }
        public string CFONE2 { get; set; }
        public string CFONE3 { get; set; }
        public string CEMAILS { get; set; }
        public string CCEP { get; set; }
        public string CCIDADE { get; set; }
        public string CUF { get; set; }
        public string CBAIRRO { get; set; }
        public string CRUA { get; set; }
        public Nullable<int> CNUMERO { get; set; }
    }
}
