//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorHoteleiro.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUARTO
    {
        public QUARTO()
        {
            this.HOSPEDAGEM = new HashSet<HOSPEDAGEM>();
        }
    
        public int NIDQUARTO { get; set; }
        public string CDESCRICAO { get; set; }
        public Nullable<int> NNUMERO { get; set; }
        public Nullable<int> NANDAR { get; set; }
        public Nullable<int> NMAXPESSOAS { get; set; }
        public string CESTATUS { get; set; }
        public Nullable<decimal> NVALORBASE { get; set; }
    
        public virtual ICollection<HOSPEDAGEM> HOSPEDAGEM { get; set; }
    }
}
