//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorHoteleiro.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int IDUSUARIO { get; set; }
        public string CNOME { get; set; }
        public string CEMAIL { get; set; }
        public string CFONE { get; set; }
        public string CFONE2 { get; set; }
        public string CNICK { get; set; }
        public string CSENHA { get; set; }
    }
}
